version: "3.9"

services:
  app:
    build: .
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo:27017/notification-service?authSource=admin
      SPRING_APPLICATION_NAME: notification-service

  mongo:
    image: mongo:7
    container_name: notification-service-mongo-db
    ports:
      - "27019:27017"
    volumes:
      - notification_service_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: notification-service
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  notification_service_mongo_data:
