version: "3.9"

services:
  app:
    build: .
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo:27017/order-service?authSource=admin
      SPRING_APPLICATION_NAME: order-service
    networks:
      - laba-microservices

  mongo:
    image: mongo:7
    container_name: order-service-mongo-db
    ports:
      - "27018:27017"
    volumes:
      - order_service_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: order-service
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - laba-microservices

volumes:
  order_service_mongo_data:

networks:
  laba-microservices:
    external: true