version: "3.9"

services:
  app:
    build: .
    container_name: inventory-service
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventory-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - laba-microservices

  db:
    image: postgres:16
    container_name: inventory-service-postgres-db
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - inventory_service_pgdata:/var/lib/postgresql/data
    networks:
      - laba-microservices

volumes:
  inventory_service_pgdata:

networks:
  laba-microservices:
    external: true